### ISSUE TITLE
Adding exclude list capabilities at config level

### ISSUE THREAD

**Issue by fzipi** [fzipi/go-ftw#25]
Sometimes we have tests that work only for some specific platform (like apache). But we want to run all tests in many platform, to see that everything keeps working.

Adding an `excludelist` at the config would allow us to do exactly that.

**Comment by airween** [comment]
I think it's important that `excludelist` would contains tests identifiers which could be ignored, if the test failed - not skipped the test. :)

**Comment by fzipi** [comment]
So it is more an `ignorelist` maybe? We can do both.

**Comment by fzipi** [comment]
After doing a first pass, I come with this. Having three additional maps for ignore, pass or fail. 

An example is:

```yaml
testmodify:
  ignore:
    '920400-1': 'This test result must be ignored'
    ... (this is a list)
  forcepass:
    '123456-1': 'We expect this test to pass once issue github.com/.... is resolved'
    ... (this is a list)
  forcefail:
    '200200-4': 'Force fail this test until we find a solution to bug #1234'
    ... (this is a list)
```

The id of the test should match with the proper test you want to modify its results, and the text should be handy for printing in the results.

This only modifies the *results*, but the test is still executed.

What do you think?

**Comment by airween** [comment]
I don’t think we need that many kinds of lists - if case of [ftwrunner](https://github.com/digitalwave/ftwrunner) I made only one list, but that list can modify the result as this:

```
if TEST == PASSED:
    if TEST in WHITELIST:
        result = PASSED_BUT_LISTED  // this is important for user, because the test can be removed from the list 
    else:
        result = PASSED  // this is the expected
else:
    if TEST in WHITELIST:
        result = FAILED_BUT_LISTED // this is the expected
    else:
        result = FAILED  // ops...
```
> This only modifies the _results_, but the test is still executed.

Agree. But not sure this implies the number of lists.

**Comment by fzipi** [comment]
This was implemented.
