### ISSUE TITLE
override options poorly documented?

### ISSUE THREAD

**Issue by dkegel-fastly** [fzipi/go-ftw#59]
go-ftw and ftw before it both seem to assume the server being tested is at localhost:80.

The python ftw seems to have options to change that, e.g. --destaddr=domain.com --port 443 --protocol https, at least when run with test/test_default.py (I guess that was its equivalent of cloud mode).

So does go-ftw -- see applyInputOverride and config_test.go -- but the feature appears to be poorly documented,
with no example in README.md.

**Comment by fzipi** [comment]
Good find, will add it to the docs.
