### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by dune73** [fzipi/go-ftw#62]
I'm following README. This is what happens:

```
$ go install github.com/fzipi/go-ftw@latest
can't load package: package github.com/fzipi/go-ftw@latest: can only use path@version syntax with 'go get'
```

When I do
```
$ go install github.com/fzipi/go-ftw
...
build github.com/fzipi/go-ftw: cannot load time/tzdata: malformed module path "time/tzdata": missing dot in first path element
```

Go version:
```
$ go version
go version go1.13.8 linux/amd64
```

**Comment by theseion** [comment]
Not good. `go install` should work.

**Comment by dune73** [comment]
What do I do and does the doc needs fixing?

I can't get it to work locally, but I'm also a GO noob.

**Comment by theseion** [comment]
Looking into it now ;)

**Comment by dune73** [comment]
Thank you.

**Comment by theseion** [comment]
Your're using a rather old version of go that does not yet support the format we use (at least not in its default state). The current version is 1.19. I've tested with 1.17 and it works.

**Comment by dune73** [comment]
Got you. Thanks.

For the record: Ubuntu 20.04 LTS.
